import { useState } from 'react';
import snapshot from './data/latest.json';
import { Header } from './components/Header';
import { TopicCloud } from './components/TopicCloud';
import { StoryPanel } from './components/StoryPanel';
import { StoryModal } from './components/StoryModal';
import type { HNSnapshot, HNStory } from './types/hn';

const data = snapshot as HNSnapshot;

export default function App() {
  const [selectedStory, setSelectedStory] = useState<HNStory | null>(null);

  return (
    <div className="app">
      <Header fetchedAt={data.fetchedAt} storyCount={data.stories.length} />
      <main className="app__main">
        <TopicCloud topics={data.topics} />
        <section className="panel">
          <h2 className="panel__heading">Top Stories</h2>
          <div className="story-grid">
            {data.stories.map((story) => (
              <StoryPanel key={story.id} story={story} onOpen={setSelectedStory} />
            ))}
          </div>
        </section>
      </main>
      <footer className="app__footer">
        Data refreshed daily via GitHub Actions from the{' '}
        <a href="https://hn.algolia.com/api" target="_blank" rel="noreferrer">
          HN Algolia API
        </a>
        , with AI summaries generated by Claude. Not affiliated with Y Combinator.
      </footer>

      {selectedStory && (
        <StoryModal story={selectedStory} onClose={() => setSelectedStory(null)} />
      )}
    </div>
  );
}
